### ISSUE TITLE
Feature request: more detailed example

### ISSUE THREAD

**Issue by chiester** [beanloop/react-form-helper#2]
Is it possible for someone to provide a more detailed example? Maybe showing the form with a render method?

**Comment by drager** [comment]
@chiester: Yes, we are working to obtain more documentation and examples as soon as possible. :blush:

**Comment by Pajn** [comment]
I have now pushed some examples that you can see at <https://beanloop.github.io/react-form-helper/#/examples>

If you find some information missing or have good ideas for extra examples, please let us know!
